# Nombre del proyecto (evita prefijos redundantes)
name: sist-hab

services:
  dbsh:
    image: mysql:8.1.0
    container_name: sist-hab-db-prod
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=quanium
      - MYSQL_DATABASE=sisthabpro
      - MYSQL_USER=quanium
      - MYSQL_PASSWORD=quanium
      - TZ=America/Bogota
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/sisthabpro.sql:/docker-entrypoint-initdb.d/01-sisthabpro.sql
      - ./db/usuarios.sql:/docker-entrypoint-initdb.d/02-usuarios.sql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-pquanium",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 90s
    command: --default-authentication-plugin=mysql_native_password --wait_timeout=28800 --interactive_timeout=28800 --max_allowed_packet=256M --log-error-verbosity=2
    networks:
      - app-network

  phpmyadminsh:
    image: phpmyadmin/phpmyadmin
    container_name: sist-hab-phpmyadmin-prod
    restart: always
    ports:
      - "82:80"
    environment:
      - PMA_HOST=dbsh
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=quanium
    depends_on:
      dbsh:
        condition: service_healthy
    networks:
      - app-network

  websh:
    image: sistema-habilitador-prod:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=18.16.1
    container_name: sist-hab-prod
    restart: always
    volumes:
      - imagen_data:/quanium/app/src/publico/imagen4
    ports:
      - "7777:7777"
    environment:
      # Base de datos principal (sisthabpro)
      - DB_HOST=dbsh
      - DB_PORT=3306
      - DB_USER=quanium
      - DB_PASSWORD=quanium
      - DB_NAME=sisthabpro
      # Configuración de la aplicación
      - PORT=7777
      - NODE_ENV=production
      # Seguridad JWT
      # ⚠️ JWT_SECRET se autogenera al iniciar el sistema si no existe en .env
      # No es necesario configurarlo manualmente
      - JWT_EXPIRES_IN=8h
      # CORS Origins permitidos (separados por coma, usar * para permitir todos)
      - ALLOWED_ORIGINS=*
      # NPM Configuration
      - NPM_CONFIG_LOGLEVEL=info
      - NPM_CONFIG_REGISTRY=https://registry.npmjs.org
    depends_on:
      dbsh:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --quiet --tries=1 --spider http://localhost:7777/api/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  drawio:
    image: jgraph/drawio
    container_name: sist-hab-drawio-prod
    restart: always
    ports:
      - "83:8080"
      - "84:8443"
    networks:
      - app-network

volumes:
  mysql_data:
    driver: local
  imagen_data:
    driver: local

networks:
  app-network:
    name: sist-hab-network
    driver: bridge
