version: "3.3"
services:
  dbsh:
    image: mysql:8.1.0
    container_name: sist-hab-db-prod
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=quanium
      - MYSQL_DATABASE=sisthabpro
      - MYSQL_USER=quanium
      - MYSQL_PASSWORD=quanium
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/sisthabpro.sql:/docker-entrypoint-initdb.d/sisthabpro.sql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-pquanium",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  phpmyadminsh:
    image: phpmyadmin/phpmyadmin
    container_name: sist-hab-phpmyadmin-prod
    restart: always
    ports:
      - "82:80"
    environment:
      - PMA_HOST=dbsh
      - PMA_PORT=3306
    depends_on:
      dbsh:
        condition: service_healthy
  websh:
    image: sistema-habilitador-prod:latest
    build: .
    container_name: sist-hab-prod
    restart: always
    volumes:
      - imagen_data:/quanium/app/src/publico/imagen4
    ports:
      - "7777:7777"
    environment:
      - DB_HOST=dbsh
      - DB_PORT=3306
      - DB_USER=quanium
      - DB_PASSWORD=quanium
      - DB_NAME=sisthabpro
    depends_on:
      dbsh:
        condition: service_healthy
  drawio:
    image: jgraph/drawio
    container_name: sist-hab-drawio-prod
    restart: always
    ports:
      - "83:8080"
      - "84:8443"

volumes:
  mysql_data:
    driver: local
  imagen_data:
    driver: local
